import { Anthropic } from '@anthropic-ai/sdk';
import type {
  AgentSessionEvent,
  AgentSessionMessage,
  AgentSessionRequest,
  AgentToolName,
  AgentPatchEvent,
  AgentPatchRequest,
  ChatMessage,
  ChatRequest,
  FilePatch,
  InlineCompletionEvent,
  InlineCompletionRequest,
  ProviderConnectionRequest,
  ProviderConnectionResult,
  ProviderId,
  StreamEvent
} from '../shared/types.js';

type ProviderCapabilities = {
  chat?: true;
  agentSession?: true;
  inlineCompletion?: true;
  agentPatch?: true;
};

type ProviderPlugin = {
  id: ProviderId;
  capabilities: ProviderCapabilities;

  streamChat?: (req: ChatRequest) => AsyncGenerator<StreamEvent>;
  streamAgentSession?: (req: AgentSessionRequest) => AsyncGenerator<AgentSessionEvent>;
  streamInlineCompletion?: (req: InlineCompletionRequest) => AsyncGenerator<InlineCompletionEvent>;
  streamAgentPatch?: (req: AgentPatchRequest) => AsyncGenerator<AgentPatchEvent>;
};

const registry = new Map<ProviderId, ProviderPlugin>();

function register(plugin: ProviderPlugin) {
  registry.set(plugin.id, plugin);
}

function getPlugin(providerId: ProviderId) {
  return registry.get(providerId);
}

register({
  id: 'anthropic',
  capabilities: { chat: true, agentSession: true },
  streamChat: streamAnthropic,
  streamAgentSession: streamAnthropicAgentSession
});

register({
  id: 'openai_compat',
  capabilities: { chat: true, agentSession: true },
  streamChat: streamOpenAICompat,
  streamAgentSession: streamOpenAICompatAgentSession
});

register({
  id: 'github_copilot',
  capabilities: { chat: true, inlineCompletion: true, agentPatch: true, agentSession: true },
  async *streamChat(req: ChatRequest): AsyncGenerator<StreamEvent> {
    const baseUrl = req.baseUrl || 'http://127.0.0.1:4141';
    const url = new URL(buildApiUrl(baseUrl, 'v1/messages'));
    url.searchParams.set('beta', 'true');

    const { system, messages } = splitSystem(req.messages);

    const resp = await fetch(url.toString(), {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        ...(req.apiKey?.trim() ? { authorization: `Bearer ${req.apiKey}` } : {})
      },
      body: JSON.stringify({
        model: req.model,
        max_tokens: req.interactionMode === 'claude_code' ? 4096 : 1024,
        system,
        messages: messages.map((m) => ({ role: m.role === 'assistant' ? 'assistant' : 'user', content: m.content })),
        stream: true
      })
    });

    if (!resp.ok || !resp.body) {
      yield { kind: 'chat', type: 'error', message: `Gateway error: ${resp.status} ${resp.statusText}` };
      yield { kind: 'chat', type: 'done' };
      return;
    }

    const reader = resp.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });

      while (true) {
        const idx = buffer.indexOf('\n\n');
        if (idx === -1) break;
        const chunk = buffer.slice(0, idx);
        buffer = buffer.slice(idx + 2);

        for (const line of chunk.split('\n')) {
          const trimmed = line.trim();
          if (!trimmed.startsWith('data:')) continue;
          const data = trimmed.slice('data:'.length).trim();
          try {
            const json = JSON.parse(data);
            if (json?.type === 'content_block_delta' && json?.delta?.type === 'text_delta') {
              const text = json.delta.text;
              if (typeof text === 'string' && text.length) {
                yield { kind: 'chat', type: 'token', text };
              }
            }
            if (json?.type === 'message_stop') {
              yield { kind: 'chat', type: 'done' };
              return;
            }
          } catch {
            // ignore
          }
        }
      }
    }

    yield { kind: 'chat', type: 'done' };
  },
  streamAgentSession: streamGitHubCopilotAgentSession,
  async *streamInlineCompletion(req: InlineCompletionRequest): AsyncGenerator<InlineCompletionEvent> {
    const prefix = req.documentText.slice(0, Math.max(0, req.cursorOffset));
    const currentLine = prefix.split('\n').at(-1) ?? '';
    const suggestion = currentLine.trim().length ? ' // TODO: refine' : '// TODO: start here';

    yield { kind: 'inline_completion', type: 'completion', text: suggestion };
    yield { kind: 'inline_completion', type: 'done' };
  },
  async *streamAgentPatch(req: AgentPatchRequest): AsyncGenerator<AgentPatchEvent> {
    yield { kind: 'agent_patch', type: 'progress', message: 'Generating patch…' };

    const header = `/*
 * Agent task: ${req.task}
 * Generated by placeholder copilot provider
 */\n\n`;

    const patches: FilePatch[] = [
      {
        operation: 'modify',
        filePath: req.activeFilePath ?? 'active-file.txt',
        newText: header + req.activeFileText
      }
    ];

    yield { kind: 'agent_patch', type: 'patch', patches };
    yield { kind: 'agent_patch', type: 'done' };
  }
});

export async function* streamChat(req: ChatRequest): AsyncGenerator<StreamEvent> {
  const plugin = getPlugin(req.providerId);
  if (!plugin?.streamChat) {
    yield { kind: 'chat', type: 'error', message: `Provider does not support chat: ${req.providerId}` };
    yield { kind: 'chat', type: 'done' };
    return;
  }
  for await (const ev of plugin.streamChat(req)) {
    yield { ...ev, kind: 'chat' };
  }
}

export async function* streamAgentSession(req: AgentSessionRequest): AsyncGenerator<AgentSessionEvent> {
  const plugin = getPlugin(req.providerId);
  if (!plugin?.streamAgentSession) {
    yield { kind: 'agent_session', type: 'error', message: `Provider does not support agent session: ${req.providerId}` };
    yield { kind: 'agent_session', type: 'done' };
    return;
  }
  yield* plugin.streamAgentSession(req);
}

export async function* streamInlineCompletion(req: InlineCompletionRequest): AsyncGenerator<InlineCompletionEvent> {
  const plugin = getPlugin(req.providerId);
  if (!plugin?.streamInlineCompletion) {
    yield { kind: 'inline_completion', type: 'error', message: `Provider does not support inline completion: ${req.providerId}` };
    yield { kind: 'inline_completion', type: 'done' };
    return;
  }
  yield* plugin.streamInlineCompletion(req);
}

export async function* streamAgentPatch(req: AgentPatchRequest): AsyncGenerator<AgentPatchEvent> {
  const plugin = getPlugin(req.providerId);
  if (!plugin?.streamAgentPatch) {
    yield { kind: 'agent_patch', type: 'error', message: `Provider does not support agent patch: ${req.providerId}` };
    yield { kind: 'agent_patch', type: 'done' };
    return;
  }
  yield* plugin.streamAgentPatch(req);
}

export async function checkProviderConnection(req: ProviderConnectionRequest): Promise<ProviderConnectionResult> {
  try {
    if (!req.model.trim()) {
      return { ok: false, message: 'Model is required.' };
    }

    if (req.providerId === 'github_copilot') {
      const baseUrl = req.baseUrl || 'http://127.0.0.1:4141';
      const url = buildApiUrl(baseUrl, 'v1/models');
      const resp = await fetch(url, { method: 'GET' });
      return resp.ok
        ? { ok: true, message: `Gateway reachable at ${baseUrl}.` }
        : { ok: false, message: describeHttpFailure('Copilot gateway', resp.status, resp.statusText) };
    }

    if (req.providerId === 'openai_compat') {
      if (!req.baseUrl?.trim()) {
        return { ok: false, message: 'Base URL is required for OpenAI-compatible providers.' };
      }
      if (!req.apiKey?.trim()) {
        return { ok: false, message: 'API key is required for OpenAI-compatible providers.' };
      }
      const url = buildApiUrl(req.baseUrl, 'v1/models');
      const resp = await fetch(url, {
        method: 'GET',
        headers: {
          authorization: `Bearer ${req.apiKey}`
        }
      });
      return resp.ok
        ? { ok: true, message: `Provider reachable at ${req.baseUrl}.` }
        : { ok: false, message: describeHttpFailure('Provider', resp.status, resp.statusText) };
    }

    if (!req.apiKey?.trim()) {
      return { ok: false, message: 'API key is required for Anthropic.' };
    }

    const baseUrl = req.baseUrl?.trim() || 'https://api.anthropic.com';
    const resp = await fetch(buildApiUrl(baseUrl, 'v1/models'), {
      method: 'GET',
      headers: {
        'x-api-key': req.apiKey,
        'anthropic-version': '2023-06-01'
      }
    });

    if (resp.status === 404) {
      return await probeAnthropicMessagesEndpoint(req, baseUrl);
    }

    return resp.ok
      ? { ok: true, message: `Anthropic-compatible endpoint reachable at ${baseUrl}.` }
      : { ok: false, message: describeHttpFailure('Anthropic', resp.status, resp.statusText) };
  } catch (error) {
    return {
      ok: false,
      message: describeConnectionError(error)
    };
  }
}

async function probeAnthropicMessagesEndpoint(req: ProviderConnectionRequest, baseUrl: string): Promise<ProviderConnectionResult> {
  const resp = await fetch(buildApiUrl(baseUrl, 'v1/messages'), {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': req.apiKey ?? '',
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: req.model,
      max_tokens: 1,
      stream: false,
      messages: [{ role: 'user', content: 'ping' }]
    })
  });

  if (resp.ok) {
    return { ok: true, message: `Anthropic-compatible endpoint reachable at ${baseUrl}.` };
  }

  if (resp.status === 400) {
    const detail = await safeReadErrorMessage(resp);
    return {
      ok: false,
      message: detail || 'Anthropic-compatible endpoint reached, but the request was rejected. Check the model name and request format.'
    };
  }

  return {
    ok: false,
    message: describeHttpFailure('Anthropic', resp.status, resp.statusText)
  };
}

async function safeReadErrorMessage(resp: Response) {
  try {
    const body = await resp.json() as { error?: { message?: string } | string; message?: string };
    if (typeof body.error === 'string' && body.error.trim()) {
      return body.error;
    }
    if (body.error && typeof body.error === 'object' && typeof body.error.message === 'string' && body.error.message.trim()) {
      return body.error.message;
    }
    if (typeof body.message === 'string' && body.message.trim()) {
      return body.message;
    }
  } catch {
    // ignore
  }
  return '';
}

const AGENT_TOOL_NAMES: AgentToolName[] = ['list_dir', 'read_file', 'apply_patch', 'write_file', 'run_command', 'ask_user'];

type RawAgentMessageBlock = {
  type?: string;
  text?: string;
  id?: string;
  name?: string;
  input?: unknown;
};

type RawAgentMessageResponse = {
  content?: RawAgentMessageBlock[];
  stop_reason?: string | null;
  error?: { message?: string } | string;
  message?: string;
};

type RawOpenAIToolCall = {
  id?: string;
  type?: string;
  function?: {
    name?: string;
    arguments?: string;
  };
};

type RawOpenAIChatCompletionResponse = {
  choices?: Array<{
    finish_reason?: string | null;
    message?: {
      content?: string | Array<{ type?: string; text?: string }> | null;
      tool_calls?: RawOpenAIToolCall[];
    };
  }>;
  error?: { message?: string } | string;
  message?: string;
};

type RawOpenAIChoice = NonNullable<RawOpenAIChatCompletionResponse['choices']>[number];
type RawOpenAIMessageContent = NonNullable<RawOpenAIChoice['message']>['content'];

function isAgentToolName(value: unknown): value is AgentToolName {
  return typeof value === 'string' && AGENT_TOOL_NAMES.includes(value as AgentToolName);
}

function buildAgentToolDefinitions() {
  return [
    {
      name: 'list_dir',
      description: 'List files and folders in a workspace directory before reading or editing.',
      input_schema: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Relative or absolute directory path. Optional.' }
        },
        additionalProperties: false
      }
    },
    {
      name: 'read_file',
      description: 'Read a text file from the workspace.',
      input_schema: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Relative or absolute file path.' }
        },
        required: ['path'],
        additionalProperties: false
      }
    },
    {
      name: 'apply_patch',
      description: 'Apply exact-text replacements to an existing text file.',
      input_schema: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Relative or absolute file path.' },
          replacements: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                oldText: { type: 'string' },
                newText: { type: 'string' }
              },
              required: ['oldText', 'newText'],
              additionalProperties: false
            }
          },
          oldText: { type: 'string' },
          newText: { type: 'string' }
        },
        required: ['path'],
        additionalProperties: false
      }
    },
    {
      name: 'write_file',
      description: 'Write the full contents of a file. Prefer for new files or full rewrites.',
      input_schema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          content: { type: 'string' }
        },
        required: ['path', 'content'],
        additionalProperties: false
      }
    },
    {
      name: 'run_command',
      description: 'Run a shell command in the workspace terminal and capture stdout/stderr.',
      input_schema: {
        type: 'object',
        properties: {
          command: { type: 'string' },
          timeoutMs: { type: 'number' }
        },
        required: ['command'],
        additionalProperties: false
      }
    },
    {
      name: 'ask_user',
      description: 'Ask the user a focused follow-up question or present 2 to 4 implementation plans with short tradeoffs, then wait for their answer before continuing.',
      input_schema: {
        type: 'object',
        properties: {
          prompt: { type: 'string', description: 'The question to show to the user.' },
          kind: {
            type: 'string',
            enum: ['question', 'plan'],
            description: 'Use plan when presenting alternative implementation approaches.'
          },
          options: {
            type: 'array',
            items: {
              oneOf: [
                { type: 'string' },
                {
                  type: 'object',
                  properties: {
                    value: { type: 'string' },
                    label: { type: 'string' },
                    description: { type: 'string' },
                    recommended: { type: 'boolean' }
                  },
                  required: ['value'],
                  additionalProperties: false
                }
              ]
            },
            description: 'Optional short list of choices or richer choice cards.'
          },
          allowFreeform: {
            type: 'boolean',
            description: 'Whether the user may type a custom response.'
          }
        },
        required: ['prompt'],
        additionalProperties: false
      }
    }
  ];
}

function mapAgentSessionMessages(messages: AgentSessionMessage[]) {
  return messages.map((message) => ({
    role: message.role,
    content: message.content.map((block) => {
      if (block.type === 'text') {
        return { type: 'text', text: block.text };
      }
      if (block.type === 'tool_result') {
        return {
          type: 'tool_result',
          tool_use_id: block.toolUseId,
          content: block.content,
          is_error: block.isError ?? false
        };
      }
      return {
        type: 'tool_use',
        id: block.id,
        name: block.name,
        input: block.input
      };
    })
  }));
}

function mapAgentSessionMessagesToOpenAI(messages: AgentSessionMessage[]) {
  const mapped: Array<Record<string, unknown>> = [];

  for (const message of messages) {
    if (message.role === 'assistant') {
      const text = message.content
        .filter((block) => block.type === 'text')
        .map((block) => block.text)
        .join('\n\n');
      const toolCalls = message.content
        .filter((block) => block.type === 'tool_use')
        .map((block) => ({
          id: block.id,
          type: 'function',
          function: {
            name: block.name,
            arguments: JSON.stringify(block.input)
          }
        }));

      if (text || toolCalls.length > 0) {
        mapped.push({
          role: 'assistant',
          content: text || null,
          ...(toolCalls.length > 0 ? { tool_calls: toolCalls } : {})
        });
      }
      continue;
    }

    const text = message.content
      .filter((block) => block.type === 'text')
      .map((block) => block.text)
      .join('\n\n');

    if (text) {
      mapped.push({ role: 'user', content: text });
    }

    for (const block of message.content) {
      if (block.type !== 'tool_result') continue;
      mapped.push({
        role: 'tool',
        tool_call_id: block.toolUseId,
        content: block.content
      });
    }
  }

  return mapped;
}

function buildOpenAIToolDefinitions() {
  return buildAgentToolDefinitions().map((tool) => ({
    type: 'function',
    function: {
      name: tool.name,
      description: tool.description,
      parameters: tool.input_schema
    }
  }));
}

async function requestAnthropicCompatibleAgentMessage(
  req: AgentSessionRequest,
  options: {
    baseUrl: string;
    headers?: Record<string, string>;
    beta?: boolean;
    targetLabel: string;
  }
) {
  const url = new URL(buildApiUrl(options.baseUrl, 'v1/messages'));
  if (options.beta) {
    url.searchParams.set('beta', 'true');
  }

  const resp = await fetch(url.toString(), {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      ...(options.headers ?? {})
    },
    body: JSON.stringify({
      model: req.model,
      system: req.system,
      max_tokens: req.maxTokens ?? 4096,
      temperature: req.temperature,
      messages: mapAgentSessionMessages(req.messages),
      tools: buildAgentToolDefinitions(),
      tool_choice: { type: 'auto' }
    })
  });

  if (!resp.ok) {
    const detail = await safeReadErrorMessage(resp);
    throw new Error(detail || describeHttpFailure(options.targetLabel, resp.status, resp.statusText));
  }

  return await resp.json() as RawAgentMessageResponse;
}

async function requestOpenAICompatibleAgentMessage(req: AgentSessionRequest) {
  if (!req.baseUrl) {
    throw new Error('Missing baseUrl for OpenAI-compatible provider');
  }
  if (!req.apiKey) {
    throw new Error('Missing apiKey for OpenAI-compatible provider');
  }

  const resp = await fetch(buildApiUrl(req.baseUrl, 'v1/chat/completions'), {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${req.apiKey}`
    },
    body: JSON.stringify({
      model: req.model,
      messages: [{ role: 'system', content: req.system }, ...mapAgentSessionMessagesToOpenAI(req.messages)],
      temperature: req.temperature,
      max_tokens: req.maxTokens ?? 4096,
      tools: buildOpenAIToolDefinitions(),
      tool_choice: 'auto',
      stream: false
    })
  });

  if (!resp.ok) {
    const detail = await safeReadErrorMessage(resp);
    throw new Error(detail || describeHttpFailure('Provider', resp.status, resp.statusText));
  }

  return await resp.json() as RawOpenAIChatCompletionResponse;
}

async function* emitAgentMessageResponse(response: RawAgentMessageResponse): AsyncGenerator<AgentSessionEvent> {
  const content = Array.isArray(response.content) ? response.content : [];

  for (const block of content) {
    if (block.type === 'text' && typeof block.text === 'string' && block.text.length) {
      yield { kind: 'agent_session', type: 'text', text: block.text };
      continue;
    }

    if (block.type === 'tool_use' && typeof block.id === 'string' && isAgentToolName(block.name) && block.input && typeof block.input === 'object') {
      yield {
        kind: 'agent_session',
        type: 'tool_use',
        id: block.id,
        name: block.name,
        input: block.input as Record<string, unknown>
      };
    }
  }

  yield {
    kind: 'agent_session',
    type: 'done',
    stopReason: typeof response.stop_reason === 'string' ? response.stop_reason : undefined
  };
}

function readOpenAIMessageText(content: RawOpenAIMessageContent) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content
    .filter((block) => block?.type === 'text' && typeof block.text === 'string')
    .map((block) => block.text as string)
    .join('');
}

async function* emitOpenAICompatibleAgentResponse(response: RawOpenAIChatCompletionResponse): AsyncGenerator<AgentSessionEvent> {
  const choice = response.choices?.[0];
  const message = choice?.message;
  const text = readOpenAIMessageText(message?.content);

  if (text) {
    yield { kind: 'agent_session', type: 'text', text };
  }

  for (const toolCall of message?.tool_calls ?? []) {
    if (toolCall.type !== 'function' || typeof toolCall.id !== 'string' || !isAgentToolName(toolCall.function?.name)) {
      continue;
    }

    let input: Record<string, unknown> = {};
    const rawArguments = toolCall.function?.arguments;
    if (typeof rawArguments === 'string' && rawArguments.trim()) {
      try {
        const parsed = JSON.parse(rawArguments) as unknown;
        if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
          throw new Error('Tool arguments must be a JSON object');
        }
        input = parsed as Record<string, unknown>;
      } catch (error) {
        yield {
          kind: 'agent_session',
          type: 'error',
          message: error instanceof Error ? `Invalid tool arguments for ${toolCall.function?.name}: ${error.message}` : `Invalid tool arguments for ${toolCall.function?.name}`
        };
        yield {
          kind: 'agent_session',
          type: 'done',
          stopReason: typeof choice?.finish_reason === 'string' ? choice.finish_reason : undefined
        };
        return;
      }
    }

    yield {
      kind: 'agent_session',
      type: 'tool_use',
      id: toolCall.id,
      name: toolCall.function.name,
      input
    };
  }

  yield {
    kind: 'agent_session',
    type: 'done',
    stopReason: typeof choice?.finish_reason === 'string' ? choice.finish_reason : undefined
  };
}

function buildApiUrl(baseUrl: string, path: string) {
  const normalizedBase = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;
  const url = new URL(normalizedBase);
  const trimmedPath = path.replace(/^\/+/, '');
  const firstSegment = trimmedPath.split('/')[0] ?? '';
  const basePath = url.pathname.replace(/\/+$/, '');
  const relativePath = firstSegment && basePath.endsWith(`/${firstSegment}`)
    ? trimmedPath.slice(firstSegment.length + 1)
    : trimmedPath;
  return new URL(relativePath, normalizedBase).toString();
}

function describeHttpFailure(target: string, status: number, statusText: string) {
  if (status === 401) {
    return `${target} rejected the credentials (401). Check the API key.`;
  }
  if (status === 403) {
    return `${target} denied access (403). The key or gateway session may not have permission.`;
  }
  if (status === 404) {
    return `${target} endpoint was not found (404). Check the base URL.`;
  }
  if (status === 429) {
    return `${target} is rate-limiting requests (429). Try again shortly.`;
  }
  if (status >= 500) {
    return `${target} is unavailable (${status}${statusText ? ` ${statusText}` : ''}).`;
  }
  return `${target} returned ${status}${statusText ? ` ${statusText}` : ''}.`;
}

function describeConnectionError(error: unknown) {
  if (!(error instanceof Error)) {
    return 'Connection check failed.';
  }

  const cause = error.cause as { code?: string } | undefined;
  if (cause?.code === 'ECONNREFUSED') {
    return 'Connection refused. The provider endpoint may not be running.';
  }
  if (cause?.code === 'ENOTFOUND') {
    return 'Host not found. Check the base URL.';
  }
  if (cause?.code === 'ETIMEDOUT') {
    return 'Connection timed out.';
  }
  if (error.message === 'fetch failed') {
    return 'Network request failed. Check the endpoint and network access.';
  }
  return error.message || 'Connection check failed.';
}

function splitSystem(messages: ChatMessage[]) {
  const system = messages.filter((m) => m.role === 'system').map((m) => m.content).join('\n\n');
  const rest = messages.filter((m) => m.role !== 'system');
  return { system: system || undefined, messages: rest };
}

async function* streamAnthropicAgentSession(req: AgentSessionRequest): AsyncGenerator<AgentSessionEvent> {
  if (!req.apiKey) {
    yield { kind: 'agent_session', type: 'error', message: 'Missing apiKey for Anthropic' };
    yield { kind: 'agent_session', type: 'done' };
    return;
  }

  try {
    const response = await requestAnthropicCompatibleAgentMessage(req, {
      baseUrl: req.baseUrl?.trim() || 'https://api.anthropic.com',
      headers: {
        'x-api-key': req.apiKey,
        'anthropic-version': '2023-06-01'
      },
      targetLabel: 'Anthropic'
    });

    yield* emitAgentMessageResponse(response);
  } catch (error) {
    yield { kind: 'agent_session', type: 'error', message: error instanceof Error ? error.message : 'Anthropic agent session failed' };
    yield { kind: 'agent_session', type: 'done' };
  }
}

async function* streamGitHubCopilotAgentSession(req: AgentSessionRequest): AsyncGenerator<AgentSessionEvent> {
  try {
    const response = await requestAnthropicCompatibleAgentMessage(req, {
      baseUrl: req.baseUrl || 'http://127.0.0.1:4141',
      headers: req.apiKey?.trim() ? { authorization: `Bearer ${req.apiKey}` } : undefined,
      beta: true,
      targetLabel: 'Copilot gateway'
    });

    yield* emitAgentMessageResponse(response);
  } catch (error) {
    yield { kind: 'agent_session', type: 'error', message: error instanceof Error ? error.message : 'Copilot agent session failed' };
    yield { kind: 'agent_session', type: 'done' };
  }
}

async function* streamOpenAICompatAgentSession(req: AgentSessionRequest): AsyncGenerator<AgentSessionEvent> {
  try {
    const response = await requestOpenAICompatibleAgentMessage(req);
    yield* emitOpenAICompatibleAgentResponse(response);
  } catch (error) {
    yield { kind: 'agent_session', type: 'error', message: error instanceof Error ? error.message : 'OpenAI-compatible agent session failed' };
    yield { kind: 'agent_session', type: 'done' };
  }
}

async function* streamAnthropic(req: ChatRequest): AsyncGenerator<StreamEvent> {
  if (!req.apiKey) {
    yield { kind: 'chat', type: 'error', message: 'Missing apiKey for Anthropic' };
    yield { kind: 'chat', type: 'done' };
    return;
  }

  const client = new Anthropic({
    apiKey: req.apiKey,
    baseURL: req.baseUrl?.trim() || undefined
  });
  const { system, messages } = splitSystem(req.messages);

  const stream = await client.messages.stream({
    model: req.model,
    system,
    temperature: req.temperature,
    max_tokens: req.interactionMode === 'claude_code' ? 4096 : 1024,
    messages: messages.map((m) => ({ role: m.role === 'assistant' ? 'assistant' : 'user', content: m.content }))
  });

  for await (const event of stream) {
    if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') {
      yield { kind: 'chat', type: 'token', text: event.delta.text };
    }
  }

  yield { kind: 'chat', type: 'done' };
}

async function* streamOpenAICompat(req: ChatRequest): AsyncGenerator<StreamEvent> {
  if (!req.baseUrl) {
    yield { kind: 'chat', type: 'error', message: 'Missing baseUrl for OpenAI-compatible provider' };
    yield { kind: 'chat', type: 'done' };
    return;
  }
  if (!req.apiKey) {
    yield { kind: 'chat', type: 'error', message: 'Missing apiKey for OpenAI-compatible provider' };
    yield { kind: 'chat', type: 'done' };
    return;
  }

  const url = buildApiUrl(req.baseUrl, 'v1/chat/completions');

  const resp = await fetch(url, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${req.apiKey}`
    },
    body: JSON.stringify({
      model: req.model,
      messages: req.messages,
      temperature: req.temperature,
      max_tokens: req.interactionMode === 'claude_code' ? 4096 : 1024,
      stream: true
    })
  });

  if (!resp.ok || !resp.body) {
    yield { kind: 'chat', type: 'error', message: `Upstream error: ${resp.status} ${resp.statusText}` };
    yield { kind: 'chat', type: 'done' };
    return;
  }

  const reader = resp.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });

    // SSE parsing (data: ...\n\n)
    while (true) {
      const idx = buffer.indexOf('\n\n');
      if (idx === -1) break;
      const chunk = buffer.slice(0, idx);
      buffer = buffer.slice(idx + 2);

      for (const line of chunk.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed.startsWith('data:')) continue;
        const data = trimmed.slice('data:'.length).trim();
        if (data === '[DONE]') {
          yield { kind: 'chat', type: 'done' };
          return;
        }
        try {
          const json = JSON.parse(data);
          const delta = json?.choices?.[0]?.delta?.content;
          if (typeof delta === 'string' && delta.length) {
            yield { kind: 'chat', type: 'token', text: delta };
          }
        } catch {
          // ignore malformed chunks
        }
      }
    }
  }

  yield { kind: 'chat', type: 'done' };
}
